name: Parse .trx Test Results
description: Parse .NET .trx test report and summarize results in step summary
inputs:
  path:
    description: 'Path to the .trx test report'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Python parser
      shell: bash
      run: python3 "${{ github.action_path }}/parse_trx-2.py" "${{ inputs.path }}" report.html

    - name: Publish report to gh-pages branch
      shell: bash
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        # Create worktree for gh-pages branch
        git fetch origin gh-pages || git checkout --orphan gh-pages
        git switch --force-create gh-pages

        # Clear existing content and copy report
        rm -rf *
        cp report.html index.html

        # Commit and push
        git add index.html
        git commit -m "Update test report at $(date -u +"%Y-%m-%d %H:%M:%S")" || echo "Nothing to commit"
        git push origin gh-pages
