name: pull-request

permissions:
  contents: write
  actions: read
  packages: read
  checks: write

on:
  workflow_call:
    inputs:
      dotnet_version:
        description: 'A version dotnet to use.'
        default: '9.0.x'
        required: false
        type: string
      solution_path:
        description: 'Path to *.sln file. By default, the root folder.'
        required: false
        type: string
      test_path:
        description: 'Path to *.dll files of tests. By default, it is `*.Tests.dll`.'
        default: '*.Tests.dll'
        required: false
        type: string
    secrets:
      packages_read_token:
        required: true
      push_code_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:      
      - name: Checkout caller repository
        uses: actions/checkout@v4
       
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Configure NuGet
        run: |
          mkdir -p packages
          dotnet new nugetconfig --name nuget.config --output ./packages
          dotnet nuget add source --name github --username ${{ github.actor }} --password ${{ secrets.packages_read_token }} --store-password-in-clear-text "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --configfile ./packages/nuget.config

      - name: Restore
        run: dotnet restore ${{ inputs.solution_path }} --configfile ./packages/nuget.config

      - name: Build
        run: dotnet build ${{ inputs.solution_path }} --configuration Release --no-restore --output built

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: built
          path: built
          retention-days: 1
          if-no-files-found: error
          overwrite: true
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4

      - name: Download the built folder
        uses: actions/download-artifact@v4
        with:
          name: built
          path: built

      - name: Check for any *.Tests.dll files
        id: check_tests
        run: |
          TEST_DLLS=$(find . -type f -name "built/${{ inputs.test_path }}")
          echo "Found test DLLs:"
          echo "$TEST_DLLS"
          if [ -n "$TEST_DLLS" ]; then
            echo "has_tests=true" >> $GITHUB_OUTPUT
          else
            echo "has_tests=false" >> $GITHUB_OUTPUT
          fi      

      - name: Setup .NET
        if: steps.check_tests.outputs.has_tests == 'true'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Unit tests
        if: steps.check_tests.outputs.has_tests == 'true'
        run:  dotnet test built/${{ inputs.test_path }} --no-build --no-restore --logger "trx;LogFileName=TestResults.trx" --filter "FullyQualifiedName!~Integration"

      - name: Unit tests skipped
        if: steps.check_tests.outputs.has_tests == 'false'
        run: echo "No tests were found"

      - name: Upload Test Results
        if: steps.check_tests.outputs.has_tests == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: "**/TestResults.trx"

      #- name: Publish Test Results
      #  if: always()
      #  uses: dorny/test-reporter@v1
      #  with:
      #    name: Test Results
      #    path: "**/TestResults.trx"
      #    reporter: dotnet-trx

      - name: Publish Test Results
        if: hashFiles('TestResults/TestResults.trx') != ''
        uses: AleksandrSmirnovB2T/CICD/.github/actions/trx-parser@master
        with:
          path: "TestResults/TestResults.trx"
          token: ${{ secrets.push_code_token }}
